spring.datasource.url=${DATABASE_URL}

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

spring.jpa.database=postgresql
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

app.jwt.secret=
app.jwt.expiration=3600000
app.jwt.refresh-expiration=86400000

